using CurrencytoTextConverter.Server.Model;
using Microsoft.AspNetCore.Mvc;

namespace CurrencytoTextConverter.Server.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CurrencyController : ControllerBase
    {
        [HttpPost("ConvertToText")]
        public IActionResult ConvertToText([FromBody] Currency currency)
        {
            string textResult;
            long integerPart;

            if (currency == null)
            {
                return BadRequest("Amount cannot be empty.");
            }
            else
            {
                // The integer and fractional parts of the currency amount are separated
                integerPart = (long)Math.Truncate(currency.Amount);
                decimal fractionalPart = currency.Amount - integerPart;

                if (integerPart.ToString().Length > 15)
                {
                    return BadRequest("Amount entered exceeds the maximum allowed Currency.");
                }

                // The integer part of the currency amount is converted to text by using the MainConverter method from the utility class
                string integerText = Utility.Utility.MainConverter(integerPart);

                // The decimal part of the currency amount is converted to text by using the DecimalConverter method from the utility class
                string decimalText = string.Empty;
                if (fractionalPart > 0)
                {
                    decimalText = Utility.Utility.DecimalConverter(fractionalPart);
                }

                // The final result is generated by combining the integer and decimal parts of the currency amount
                if (!string.IsNullOrWhiteSpace(integerText) && !string.IsNullOrWhiteSpace(decimalText))
                {
                    textResult = $"{integerText} dollars {decimalText}";
                }
                else if (!string.IsNullOrWhiteSpace(integerText))
                {
                    textResult = $"{integerText} dollars";
                }
                else if (!string.IsNullOrWhiteSpace(decimalText))
                {
                    textResult = decimalText;
                }
                else
                {
                    textResult = "Zero dollars";
                }
            }
            return Ok(new { result = textResult });
        }
    }
}
